environment:
  matrix:
    - PYTHON: "C:\\Python36"
      DISTUTILS_USE_SDK: "1"
    - PYTHON: "C:\\Python36-x64"
      DISTUTILS_USE_SDK: "1"

install:
  - "%PYTHON%\\python.exe -m pip install wheel tox"

build: off

test_script:
  - "build.cmd %PYTHON%\\python.exe -m tox"

after_test:
  - "build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*
