language: cpp

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake python3-pip
    - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

install:
    - python3 -m pip install wheel dulwich pyqt5 pyqtdeploy

script:
    - python3 --version
    - pyqtdeploy-build --sysroot /usr pext.pdy
    - cd build-*
    - qmake -qt=5
    - make
