language: cpp

install:
    # Qt5
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake qtdeclarative5-dev
    - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    # Python 3.6.4
    - BUILD_DIR=$(mktemp -d -p /tmp python-build-XXXXXX)
    - pushd $BUILD_DIR
    - wget https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tar.xz -O python.tar.xz
    - tar -xf python.tar.xz
    - cd Python-*
    - export SYSROOT=`pwd`
    - export PATH="$SYSROOT/bin:$PATH"
    - ./configure --prefix=$SYSROOT
    - make
    - make install
    - popd
    # Install pip deps
    - export PYTHONPATH=$SYSROOT/lib/python3.6/site-packages
    - pip3 install dulwich pyqt5 pyqtdeploy

script:
    - pyqtdeploy-build --verbose pext.pdy
    - cd build-*
    - $QMAKE
    - make
