language: cpp

install:
    # Qt5
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake tree
    - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    # Python 3.6.4
    - wget https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tar.xz python.tar.xz
    - tar -xfv python.tar.xz
    - cd python
    - export SYSROOT="$HOME/python_instance"
    - ./configure --prefix=$SYSROOT
    - make
    - make install
    - tree $SYSROOT
    - export PATH="$SYSROOT/bin:$PATH"
    # Install pip deps
    - pip3 install dulwich pyqt5 pyqtdeploy

script:
    - tree $SYSROOT
    - pyqtdeploy-build --verbose pext.pdy
    - cd build-*
    - qmake
    - make
