language: cpp

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake
    - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

install:
    - pip3 install dulwich pyqt5 pyqtdeploy

script:
    - python3 --version
    - pyqtdeploy-build --sysroot /usr pext.pdy
    - cd build-*
    - qmake -qt=5
    - make
