language: python
python:
    - "3.6"

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake
    - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

install:
    - pip install dulwich pyqt5 pyqtdeploy

script:
    - python3 --version
    - pyqtdeploy-build --sysroot $HOME/virtualenv/python3.6.3 pext.pdy
    - cd build-*
    - qmake -qt=5
    - make
