language: cpp

install:
    # Qt5
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    # Get all new packages
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake
    # Miniconda
    - export SYSROOT="$HOME/miniconda"
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
    - bash ~/miniconda.sh -b -p $SYSROOT
    - export PATH="$SYSROOT/bin:$PATH"
    - . $SYSROOT/bin/activate
    # Install pip deps
    - pip install --user dulwich pyqt5 pyqtdeploy
    # Set up Qmake
    - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

script:
    - pyqtdeploy-build --verbose pext.pdy
    - cd build-*
    - qmake -qt=5
    - make
